queue = []
queue.append('hungary')
print(queue)
queue.append('love')
print(queue)
queue.append('thai')
print(queue)
queue.append(555)
print(queue)
queue.pop(0) #if pop(0) is dequeued 
print(queue)
queue.pop(0)
queue.pop(0)
queue.pop(0)
print(queue)